Crown-Commercial-Service/ccs-scale-api-definitions

gm-decision-tree/decision-tree-service.yaml
guided-match/guided-match-service.yaml

Should bring it up to speed with https://github.com/Crown-Commercial-Service/ccs-scale-api-definitions/pull/28 👍

Update DT API to match GM 0.1.0 (latest PT changes)

---

gm-decision-tree/decision-tree-service.yaml
guided-match/guided-match-service.yaml

Add get-question to GM and DT APIs

---

gm-decision-tree/decision-tree-service.yaml
guided-match/guided-match-service.yaml

As requested by Tom to allow display of unit type for numeric questions and answers

Gm qtype add units

---

guided-match/guided-match-service.yaml

As discussed with Tom to allow UI to format and display the units for numerical values.

SFC-449 Add Unit to AnswerHistory

---

guided-match/guided-match-service.yaml

search-journeys API call added to support Website <-> FAT interface. Search term in, journey list out

SFC-882 Update guided-match-service.yaml

---

gm-decision-tree/decision-tree-service.yaml
guided-match/guided-match-service.yaml

Also with errorSummary now (and error enums)

Gm dt error codes

---

agreements/agreements-service.yaml
common/CCS_Standard_API_Params.yaml
common/CCS_Standard_API_Schema.yaml
common/OCDS_Schema.yaml

I think we need to discuss the use of ID as opposed to Id in the naming of objects. This is Nick following what OCDS does (which we are meant to follow) rather than what we generally do. Do we need an exception on camelCase for ID?
Also, I know the paths are hadcoded for the branch. That was so that I could check the Agreement yaml in swaggerhub. I need to check them out and then change all the links to master after this is committed

Bat updates 2

---

agreements/agreements-service.yaml
common/CCS_Standard_API_Params.yaml
common/OCDS_Schema.yaml

All paths now updated to the master branch. NB why does compare show the entire file as having changed rather than just the lines I changed?

Bat updates 2a

---

bat/oauth.yaml
catalogue/catalogue-service.yaml

Tidying up the 'account' calls which should be both tactical and common.

Sca 1877 move account to common tactical yaml

---

bat/oauth.yaml
catalogue/catalogue-service.yaml

Change response type to application/json

Sca 1877 part 3   response type

---

agreements/agreements-service.yaml

Hi Dave - made a couple of very minor description fixes based on implementing one of the new endpoints

SINF-361 - minor text tweaks for get-agreement-lots.

---

agreements/agreements-service.yaml

Documents are held at Agreement level

Remove get-lot-documents

---

agreements/agreements-service.yaml
cat/CaT-service.yaml
catalogue/catalogue-service.yaml
gm-decision-tree/decision-tree-service.yaml
guided-match/guided-match-service.yaml

Align with naming standard and add references to common.

Align with api naming std

---

cat/CaT-service.yaml

Modify and extend event-types endpoints

---

cat/CaT-service.yaml

As discussed - fixes the code gen classes

Extract nonOCDS content into EventDetailNonOCDS

---

cat/CaT-service.yaml

Needs validating with development

Align with Jira's

---

cat/CaT-service.yaml

Move get user response into dedicated type

---

cat/CaT-service.yaml

SCAT-2153- Added text field for array items to display text for radio button in front-end

---

cat/CaT-service.yaml

Add text value to question type enum to support textarea/longtext

SCAT-2153 Add text value to question type enum to support textarea/longtext

---

cat/CaT-service.yaml

Simple PR - mainly just changes response for `GET` to an array and the response type for the `PUT`
Along with a few tweaks to descriptions (happy to change any/all if alternatives preferred)

SCAT-2134 - Suppliers - minor description changes and changed response type of POST

---

journeys/journeys-service.yaml

Doesn't change structure, just re-jigs so generator can make full sense of the `Journey` schema type.

Mods for generator and ease of comprehension

---

journeys/journeys-service.yaml

Some basic validation for use in the API.

Validation properties

---

cat/CaT-service.yaml

Added new 'Monetary' questionType to cater for budget questions

SCAT-2470 - added Monetary questionType

---

cat/CaT-service.yaml

Update /GoToMarket to /publish (an event)

---

capabilities/capability-service.yaml

Hi Nick - this is a small PR with the changes I made to your CA branch following getting the Java classes generated. If you think this is ok we can merge this into yours and then create the PR to get that into master

SCAT-2918 - mini update to CA branch

---

capabilities/capability-service.yaml
cat/CaT-service.yaml

PR containing all the minor changes to the Assessments API made during the basic implementation of the core functionality.
This is now servicing working endpoints - suspect we will need further tweaks, but this will allow deployment to DEV for the UI guys to start integration.

Assessment API Tweaks

---

capabilities/capability-service.yaml

This makes the code a lot easier to comprehend 😄

Add criterion to req scores and update type names

---

cat/CaT-service.yaml

Allow buyer to retrieve attachments added by a supplier in Jaggaer.

Retrieve attachments

---

capabilities/capability-service.yaml

As discussed on Slack to support business requirement to score to 2dp.

Make score value number 2dp with examples and descs

---

cat/CaT-service.yaml

Changes to MessageSummary object to generate java classes to match response in API

SCAT-3090 changes to message summary object

---

capabilities/capability-service.yaml

Add `status` to GET assessment call (already added to GET assessments)

SCAT-4249 - return assessment status

---

cat/CaT-service.yaml

removed required in QandA

---

capabilities/capability-service.yaml

This reverts commit ef2ede3952c702f163b6aa72854beed7f988a51f.

Revert "Feature/g cloud save search (#186)"

---

cat/CaT-service.yaml

GET users endpoint with filter

Add GET /users

---

cat/CaT-service.yaml

added lotname for QandA

---

cat/CaT-service.yaml

API key changes for eSourcing/Conclave

Security changes

---

cat/CaT-service.yaml

https://crowncommercialservice.atlassian.net/browse/SCAT-8514

added start evaluation api

---

cat/CaT-service.yaml

https://crowncommercialservice.atlassian.net/browse/CAS-87

added lastUpdated date for sorting

---

cat/CaT-service.yaml

Additional data fields in response

eSourcing-EI-114 salesforce endpoint to return additional data

---

cat/CaT-service.yaml

https://crowncommercialservice.atlassian.net/browse/CAS-1112

updated dashboard status for async

---

cat/CaT-service.yaml

Data transparency API specifications added

Data transparency APIs added

---

cat/CaT-service.yaml

Added nonOCDS element for cancellationDate
to generate reponse of 
"nonOCDS": {
"tender": {
"cancellationDate": "2023-07-11T13:14:49.014061+01:00"
}
}

added NonOCDS element for cancellationDate
